#!/bin/sh -e

mkdir wine-64-build
cd wine
# apply wine-staging patchset
../wine-staging/staging/patchinstall.py --all

# Apply flags for cross-compilation
export CROSSCFLAGS="-O2 -pipe"
export CROSSCXXFLAGS="-O2 -pipe"
export CROSSLDFLAGS="-Wl,-O1"

cd ../wine-64-build
  ../wine/configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-archs=x86_64,i386

make
make prefix="$1/usr" \
    libdir="$1/usr/lib" \
    dlldir="$1/usr/lib/wine" install
