#!/bin/sh -e

ar x google-chrome-beta_*amd64.deb
tar -xf data.tar.xz -C "$1/"

rm -r "$1"/etc/cron.daily/
rm -r "$1"/opt/google/chrome-beta/cron/

#remove libwidevinecdm (segfaults on my system)
rm -r "$1"/opt/google/chrome-beta/WidevineCdm/

# Icons
for i in 16x16 24x24 32x32 48x48 64x64 128x128 256x256; do
install -Dm644 "$1"/opt/google/chrome-beta/product_logo_${i/x*/}_beta.png \
	       "$1"/usr/share/icons/hicolor/$i/apps/google-chrome-beta.png
done

# Desktop entry
sed -i \
	-e "/Exec=/i\StartupWMClass=Google-chrome-beta" \
	-e "s/x-scheme-handler\/ftp;\?//g" \
	"$1"/usr/share/applications/google-chrome-beta.desktop

# remove sources

rm -rf ~/.cache/kiss/sources/google-chrome-beta/*.deb
