#!/bin/sh -e

 export RUSTUP_TOOLCHAIN=stable
 export CARGO_TARGET_DIR=target
 cargo fetch --target "x86_64-unknown-linux-gnu"
 cargo build --frozen --release --all-features

 install -Dm0755 -t "$1/usr/bin/" "target/release/hybrid-bar"
