#!/usr/bin/sh -e

[ -z $1 ] && echo "Provide a package name" && exit 1
pkg=$1
path=$(kiss search $pkg | head -n 1)
rm -rf $pkg

mkdir $pkg
cd $pkg
cp $path/version .
cp $path/depends .
sed -i '/.* make$/d' ./depends

echo "cp * /" > ./build
chmod +x ./build

version=$(sed 's/ /-/g' ./version)
echo "http://zero-pi.ignorelist.com/${pkg}/${pkg}@${version}.tar.xz" \
  > ./sources

kiss c

cd ..

# upload source file to server
lftp vdrlake -e "put ~/.cache/kiss/bin/${pkg}/${pkg}@${version}.tar.xz; bye"
