#!/bin/sh -e

mkdir build
cd    build

meson setup ..              \
      --prefix=/usr         \
      --localstatedir=/var  \
      -D glamor=true        \
      -D xkb_output_dir=/var/lib/xkb
ninja
DESTDIR=$1 ninja install
