#!/bin/sh -e

./configure --prefix=/usr

make
make DESTDIR="$1" install

# Remove unnecessary files.
find "$1/usr/share/icons" \
    \( \
      -name 'AUTHORS' \
      -o -name 'CONTRIBUTORS' \
      -o -name 'LICENSE' \
    \) -delete
