#!/bin/sh -e

sed -e '1i\#![warn(dangerous_implicit_autorefs)]\r' \
    -i third_party/rust/allocator-api2/src/stable/vec/mod.rs

export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none
export MOZBUILD_STATE_PATH=$(pwd)/mozbuild
export CXX=g++

./mach build
MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none DESTDIR=$1 ./mach install

# Desktop file
mkdir -p $1/usr/share/applications
cp thunderbird.desktop $1/usr/share/applications/
