#!/bin/sh -e

#fix build with latest Xorg
grep -rl slave | xargs sed -i s/slave/secondary/

patch -p1 < rootless_modesetting.patch

export LDFLAGS="$LDFLAGS -Wl,-z,lazy"
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
