#!/bin/sh -e

cmake_options=(
    -B build
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_INSTALL_LIBDIR=lib
    -D CATCH_BUILD_EXAMPLES=OFF
    -D CATCH_ENABLE_COVERAGE=OFF
    -D CATCH_ENABLE_WERROR=OFF
    -D BUILD_TESTING=OFF
    -D CATCH_DEVELOPMENT_BUILD=ON
    -Wno-dev
    -D BUILD_SHARED_LIBS=OFF
)

cmake "${cmake_options[@]}"
cmake --build build
DESTDIR=$1 cmake --install build
