#!/bin/sh -e

# two CVE
patch -Np1 -i patch1.patch
patch -Np1 -i patch2.patch


./configure \
  --prefix='/usr'

make
make DESTDIR="${1}" install
rm -rf "${1}"/usr/{bin,include,lib/{pkgconfig,libtiff{,xx}.{a,so}},share}
