#!/bin/sh -e

mkdir build

sed -i 's/zext_workspace_handle_v1_activate(workspace_handle_);/const std::string command = "hyprctl dispatch workspace " + name_;\n\tsystem(command.c_str());/g' src/modules/wlr/workspace_manager.cpp # use hyprctl to switch workspaces

meson --prefix=/usr build
meson configure -Dexperimental=true build

cd build

ninja
DESTDIR=$1 ninja install
