#!/bin/sh -e

tools=('as10k1' 'hwmixvolume' 'hdajackretask' 'hda-verb' 'hdajacksensetest')

for tool in ${tools[@]}; do

(
cd $tool

./configure --prefix=/usr --sbindir=/usr/bin

make
make install

)
done
