#!/bin/sh -e

sed -i 's/fgrep/grep -F/g' check.t
sh Build.sh -r
install -D -m 755 mksh "$1/usr/bin/mksh"
install -D -m 644 mksh.1 "$1/usr/share/man/man1/mksh.1"
install -D -m 644 dot.mkshrc "$1/etc/skel/.mkshrc"
