#!/bin/sh -e

cargo fetch --locked
cargo build --frozen --release
# Binary (installed alongside plugins, symlinked from /usr/bin)
install -Dm755 target/release/fresh "$1/usr/share/fresh/fresh"
install -dm755 "$1/usr/bin"
ln -s "/usr/share/fresh/fresh" "$1/usr/bin/fresh"

# Plugins
cp -r plugins "$1/usr/share/fresh/"

# Keymaps
cp -r keymaps "$1/usr/share/fresh/"
